### ISSUE TITLE
windows系统怎么直接运行py文件不成功？

### ISSUE THREAD

**Issue by ghost** [henices/Tcp-DNS-proxy#14]
以前直接下载全部，运行 tcpdns.py 就行了。现在双击后一闪而逝，非得去运行 tcpdns.exe 。
　　图片上传不上来。
　　1. 直接双击运行错误：ImportError: No module named pylru
　　2. 在cmd窗口运行错误：SyntaxError: invalid syntax

**Comment by lix5027** [comment]
check dns packet函数貌似下面这句有点问题
        test = (ip_len == '\x00\x04' and answer_class == '\x00\x01' and \
                answer_type == '\x00\x01')

比如我nslookup tv.sohu.com 211.167.230.100 
时候会得到2行ipv6地址,1行ipv4地址(118.244.253.88)

但是用到tcpdns.py代理中,check函数会把这行ipv4地址test不通过,导致转发给客户的时候丢失了ipv4地址.

请帮忙看一下test函数是否有问题,谢谢!

**Comment by henices** [comment]
@lix5027 开一个新issue吧
