### ISSUE TITLE
check dns packet (test part)

### ISSUE THREAD

**Issue by lix5027** [henices/Tcp-DNS-proxy#18]
check dns packet函数貌似下面这句有点问题
test = (ip_len == '\x00\x04' and answer_class == '\x00\x01' and \
answer_type == '\x00\x01')

比如我nslookup tv.sohu.com 211.167.230.100 
时候会得到2行ipv6地址,1行ipv4地址(118.244.253.88)

但是用到tcpdns.py代理中,check函数会把这行ipv4地址test不通过,导致转发给客户的时候丢失了ipv4地址.

请帮忙看一下test函数是否有问题,谢谢!

**Comment by henices** [comment]
能否用wireshark抓个包，放上来看看。另外使用的是TCP的DNS报文转发，还是UDP的DNS报文转发？

**Comment by lix5027** [comment]
是UDP,稍等我去尝试下抓包

**Comment by henices** [comment]
我这里抓包看了下，估计是有问题。

**Comment by lix5027** [comment]
好像无法上传cap文件? 查询时候会有一条type A  和一条tpyeAAA   AAA里面有ipv6信息,这个没问题
typeA 里包含了ipv4的反馈地址, dns用 211.167.230.100  的type A包就会被check函数过滤掉
用dns114.114.114.114 到是没问题.

不知道是哪里出错了
![dns packet](https://cloud.githubusercontent.com/assets/8099640/6013373/ba95c682-ab8e-11e4-8351-f0784b751055.gif)

**Comment by henices** [comment]
commit 3d75ead3b0e08d5ab4fb , 测试一下

**Comment by lix5027** [comment]
测试通过,OK了,老大真乃神速!赞!

**Comment by henices** [comment]
没有判断ipv6地址的情况，现在加了判断。
