### ISSUE TITLE
windows下tcpdns.exe不能用了。tcpdns.py倒是可以在windows下用。

### ISSUE THREAD

**Issue by a8l1vy** [henices/Tcp-DNS-proxy#19]
大哥我又来了，我不会看代码，小菜鸟。终于搞定以后如何在 windows 下运行了。
windows 8.1 下的安装教程要更新。其实不用安装 Visual Studio 大程序。我安装了搞得的我的网卡多出来一大堆虚拟网卡，修改什么设置非得去对应的虚拟网卡属性下修改，完全搞不懂了，intel 的网卡管理软件不能识别 Visual Studio 带的东西 hyper-v 创建的虚拟网卡，控制不了无线了只能交给 windows 自己控制（我安装的时候就没注意全都安装了）。Visual Studio 里面自带 hyper-v 虚拟机，扰得 Oracle VM VirtualBox 不能运行。汗啊。完全没法卸载干净。只得重新装系统。 - -!

1. 
（1）下载 Tcp-DNS-proxy 右下角 download zip 解压缩
（2）pylru 目录里是空的，在 https://github.com/jlhutch/pylru 点右下角的 download zip 下载解压缩到 D:\Tcp-DNS-proxy-master\third_party\pylru
最后 pylru.py 文件和其他文件是同级位置的。
位置是这样 D:\Tcp-DNS-proxy-master\third_party\pylru\pylru.py
（3）安装 Python 2.7.9
https://www.python.org/downloads/release/python-279/
下载页面下方的 Windows x86-64 MSI installer （64位） 或者 Windows x86 MSI installer （32位）
（4）安装 Microsoft Visual C++ Compiler for Python 2.7 （如果不安装 Microsoft Visual C++ Compiler for Python 2.7 下面的某个步骤会出错，提示安装这个玩意，然后给出一个短链接，跳转后是 Microsoft Visual C++ Compiler for Python 2.7 的英文页面）
http://www.microsoft.com/en-us/download/details.aspx?id=44266
（5）将自带目录下的 tcpdns.json.example 修改成 tcpdns.json
（6）将 tcpdns.json 中的内容 0.0.0.0 修改为 127.0.0.1 网卡设置里 ipv4 dns 地址就填写 127.0.0.1

2. 安装 pip.exe 
下载 https://raw.github.com/pypa/pip/master/contrib/get-pip.py （目标另存为保存）
将 get-pip.py 放到 C:\Python27  目录下。
cmd 窗口工作目录切换到 C:\Python27 输入命令 python.exe get-pip.py 

3. 安装 python gevent
cmd 窗口工作目录切换到 C:\Python27
直接输入下面这个运行（全部输入） 
C:\Python27\Scripts\pip.exe install gevent
---------------------------以上全部都显示运行成功不出错，再在桌面创建一个 bat 文件运行。

4. 桌面创建一个 txt 文本
内容输入 
C:\Python27\python.exe D:\Tcp-DNS-proxy-master\tcpdns.py -f D:\Tcp-DNS-proxy-master\tcpdns.json
将文本 txt 后缀修改为 bat ，确认后双击运行。

5. 需要修改 exe 文件。
现在 tcpdns.exe 的不能运行了。bat 文件内容是这样
start D:\Tcp-DNS-proxy-master\win\tcpdns.exe -f D:\Tcp-DNS-proxy-master\tcpdns.json
它提示找不到 tcpdns.json 位置。应该是 exe 程序里内容错误。
窗口会一闪而逝，快速截个图是这样的。里面出现双反斜杠，程序本身代码问题吧？
截图：
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!107&authkey=!ANOUduDnTXAXwVI&v=3&ithint=photo%2cpng

**Comment by a8l1vy** [comment]
1. 
（5）将自带目录下的 tcpdns.json.example 修改成 tcpdns.json

**Comment by a8l1vy** [comment]
1. 
（6）将 tcpdns.json 中的内容 0.0.0.0 修改为 127.0.0.1
网卡设置里 ipv4 dns 地址就填写 127.0.0.1

----------------------------------
新版本不如原来的爽啊。test dns speed 在网络不好的情况下时间等待超长，而且 ipv6 隧道的域名请求在windows 一连接无线或者一拨号就开始查询了。tcpdns 还要测速。微软隧道就连接不上了。
没有以前那种查询一个显示一个域名的记录，看不成不爽啊。不然就得用 Wireshark 抓包看。

**Comment by a8l1vy** [comment]
1. 
（4）安装 Microsoft Visual C++ Compiler for Python 2.7 （上面中文直接改 en-us 为 zh-cn 发现地址打不开。）
http://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by henices** [comment]
1. test dns speed 在 tcpdns.json 里有设置开关，可以不使用。
2. 原来显示域名记录的现在变成调试信息了，可以尝试  -d  选项

python tcpdns.py -f tcpdns.json -d

**Comment by henices** [comment]
我看了报的错，说是找不到 tcpdns.json 的配置文件，你自己再检查一下。

**Comment by a8l1vy** [comment]
调试输出这么整齐，原来版本短时间内域名请求一多，domain开头就对不齐了。

重新编辑了一下目录，输出的错误不对了。系统 环境变量我也添加了。
bat 文件 截图：
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!108&authkey=!AGkFKyXw97G1Z-c&v=3&ithint=photo%2cPNG
运行框出错截图：
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!109&authkey=!AMFDW8kVi0uCXoE&v=3&ithint=photo%2cpng

**Comment by henices** [comment]
这个错误是使用的tcpdns.json 和 exe 版本不匹配导致。

请重新使用　win\toexe.bat 生成新的 tcpdns.exe

**Comment by a8l1vy** [comment]
不能生成，某个部件不支持64位。
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!110&authkey=!AKAvIYPIZg1SUFc&v=3&ithint=photo%2cPNG

**Comment by henices** [comment]
兄弟，如果以右键以管理员身份运行出现不同错误的那图路径不对啊。
你自己看看。

我重新生成一个新的tcpdns.exe 放上去吧。

**Comment by a8l1vy** [comment]
我也知道路径不对，那本来就在win目录下，我没挪地方。

全部文件都没动，除了上面我自己操作步骤里提到的。其他一概都没动。d盘主目录上边发的时候略去了罢了。

**Comment by henices** [comment]
已经更新了windows的安装步骤，非常感谢。

tcpdns.exe 也更新了，请下载测试一下

https://github.com/henices/Tcp-DNS-proxy/raw/master/win/tcpdns.exe

**Comment by a8l1vy** [comment]
全部都可以了。
tcpdns.json 截图：
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!115&authkey=!AM9NGe2FK2SSW0o&v=3&ithint=photo%2cPNG

运行 tcpdns.py 的 bat 文件：
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!122&authkey=!AB-AolrFA5Gwr48&ithint=folder%2c

运行结果正常：
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!123&authkey=!AKeKdzMyE4QguWI&ithint=folder%2c

运行 tcpdns.exe 的 bat 文件：
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!124&authkey=!AOzyiNgKbGeUrhM&ithint=folder%2c

运行结果正常：
https://onedrive.live.com/redir?resid=46B5E9BC655920D2!126&authkey=!ADEq1e9_j6y2Opk&v=3&ithint=photo%2cPNG
