### ISSUE TITLE
Ubuntu socket.error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by codejam1024** [henices/Tcp-DNS-proxy#21]
Ubuntu socket.error: [Errno 98] Address already in use

**Comment by henices** [comment]
execute  ```netstat -anup``` to see if udp port 53 is already used.
in my match:

```bash
sudo netstat -anup
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 0.0.0.0:53              0.0.0.0:*                           1033/python     ```

**Comment by codejam1024** [comment]
udp        0      0 127.0.1.1:53            0.0.0.0:*                           932/dnsmasq

**Comment by henices** [comment]
disable dnsmasq and it will works. 

In fedora:
virsh net-autostart --disable default

reboot
