### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by vi5i0n** [henices/Tcp-DNS-proxy#22]
[2015-06-25 10:27:58,874][ERROR] 208.67.222.222:53, timed out
Segmentation fault (core dumped)

 Linux  python2.7.10 运行两个小时左右就会出现Segmentation fault (core dumped),程序终止。

**Comment by henices** [comment]
什么时候开始出现这种情况？在我的Fedora上运行的很好。

能把core文件给我吗？

**Comment by vi5i0n** [comment]
昨天升级最新版就出现这问题。Raspberry Pi 上的Archlinux （Linux linsirpi 3.10.19-1-ARCH #1 PREEMPT Mon Nov 18 02:31:07 EET 2013 armv6l GNU/Linux）core文件已发你gmail

**Comment by henices** [comment]
稳定重现吗? 还有那个core文件解压不成功啊。

```
> lz4 -d core.python2.0.430cc8e82b034545949da419a8f03fc6.1712.1435199287000000.lz4 
Decoding file core.python2.0.430cc8e82b034545949da419a8f03fc6.1712.1435199287000000 
Error 44 : Unrecognized header : file cannot be decoded
```

**Comment by vi5i0n** [comment]
嗯，换了Armv7就不再有这问题了，估计还是内核的问题！
