### ISSUE TITLE
运行出错： Daemon无法导入(Python2.7.11)

### ISSUE THREAD

**Issue by wangyq** [henices/Tcp-DNS-proxy#27]
运行出错： Daemon无法导入。出错信息如下：
Traceback (most recent call last):
  File "tcpdns.py", line 369, in <module>
    from daemon import Daemon
ImportError: cannot import name Daemon

所有的包都安装成功，但是打开lib/python2.7/site-packages/daemon/daemon.py, 没有发现Daemon类的定义。why?
运行环境：
Linux 内核： 3.x
Python 2.7.11

**Comment by henices** [comment]
用的是　https://github.com/serverdensity/python-daemon/blob/master/daemon.py
需要先更新一下submodule

```
cd Tcp-DNS-proxy
 git submodule update --init --recursive
```

**Comment by sinri** [comment]
In Debian 9 and Python 2.7.13, it does not work to call `git submodule update --init --recursive` only. 
But run this,
    
    cd Tcp-DNS-proxy
    wget https://raw.githubusercontent.com/serverdensity/python-daemon/master/daemon.py

Then the daemon would be found.
