### ISSUE TITLE
ImportError: cannot import name Daemon

### ISSUE THREAD

**Issue by yaoguaishou** [henices/Tcp-DNS-proxy#30]
运行sudo python tcpdns.py -f tcpdns.json时报错
Traceback (most recent call last):
  File "tcpdns.py", line 369, in <module>
    from daemon import Daemon
ImportError: cannot import name Daemon

**Comment by yaoguaishou** [comment]
@yeahWu 
球帮助

**Comment by yaoguaishou** [comment]
已经解决 
下载https://github.com/serverdensity/python-daemon/blob/master/daemon.py 到tcp-dns目录下即可。
版权属于：Linsir's Blog
原文地址：http://linsir.org/post/Raspberry_Pi_Tcp_Dnsmasq_cache_server

**Comment by yeahwu** [comment]
嗯，为毛要艾特俺？
