### ISSUE TITLE
Traceback (most recent call last):   File "tcpdns.py", line 40, in <module>     from pylru import lrucache ImportError: No module named pylru

### ISSUE THREAD

**Issue by js1553274580** [henices/Tcp-DNS-proxy#33]
Traceback (most recent call last):
  File "tcpdns.py", line 40, in <module>
    from pylru import lrucache
ImportError: No module named pylru
请问这个问题怎么解决

**Comment by henices** [comment]
cd Tcp-DNS-proxy
git submodule update --init --recursive
