### ISSUE TITLE
我运行了pip install daemon，为何最后还是显示ImportError: cannot import name Daemon

### ISSUE THREAD

**Issue by luckypoem** [henices/Tcp-DNS-proxy#35]
hi.

bogon:tcp-dns-proxy brite$ python tcpdns.py -f tcpdns.json.example
Traceback (most recent call last):
  File "tcpdns.py", line 369, in <module>
    from daemon import Daemon
ImportError: cannot import name Daemon
bogon:tcp-dns-proxy brite$ pip install daemon
Collecting daemon
  Downloading https://files.pythonhosted.org/packages/c3/e6/e6ba191d924c1066a5fd1bc90c52e7cc8ee21e0358a5da979cca6bc0b7ff/daemon-1.2.tar.gz
Building wheels for collected packages: daemon
  Running setup.py bdist_wheel for daemon ... done
  Stored in directory: /Users/brite/Library/Caches/pip/wheels/29/df/66/e280fe56338cf31b3ed74dd090b2cbfee0d8d1d679e9f778e5
Successfully built daemon
Installing collected packages: daemon
Successfully installed daemon-1.2
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bogon:tcp-dns-proxy brite$ python tcpdns.py -f tcpdns.json.example
Traceback (most recent call last):
  File "tcpdns.py", line 369, in <module>
    from daemon import Daemon
ImportError: cannot import name Daemon
bogon:tcp-dns-proxy brite$

谢谢

**Comment by henices** [comment]
please follow the installtaion instructions. Do not install the daemon in pip.

Use  https://github.com/serverdensity/python-daemon instead

**Comment by henices** [comment]
git submodule update --init --recursive

**Comment by luckypoem** [comment]
在我克隆下来的你这个目录Tcp-DNS-proxy里运行git submodule update --init --recursive并无反应。我看了一下https://github.com/henices/Tcp-DNS-proxy ，发现third_party目录并非快捷方式，难怪
‘运行git submodule update --init --recursive并无反应’。我看到https://gitee.com/Yieazy/Tcp-DNS-proxy ，那里的third_party目录是快捷方式，我克隆那里的Tcp-DNS-proxy下来，然后进去，运行
git submodule update --init --recursive有反应：

yudeMacBook-Air:Tcp-DNS-proxy brite$ git submodule update --init --recursive
Submodule 'third_party/pylru' (https://github.com/jlhutch/pylru.git) registered for path 'third_party/pylru'
Submodule 'third_party/python-daemon' (https://github.com/serverdensity/python-daemon.git) registered for path 'third_party/python-daemon'
Cloning into 'third_party/pylru'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 281 (delta 8), reused 27 (delta 5), pack-reused 248
Receiving objects: 100% (281/281), 93.11 KiB | 65.00 KiB/s, done.
Resolving deltas: 100% (139/139), done.
Checking connectivity... done.
Submodule path 'third_party/pylru': checked out '2f9d1f8b33809a32aa510304b6c3da41461f2f41'
Cloning into 'third_party/python-daemon'...
remote: Enumerating objects: 156, done.
remote: Total 156 (delta 0), reused 0 (delta 0), pack-reused 156
Receiving objects: 100% (156/156), 38.90 KiB | 52.00 KiB/s, done.
Resolving deltas: 100% (51/51), done.
Checking connectivity... done.
Submodule path 'third_party/python-daemon': checked out 'a68d5718221cfe7c4447337b6ccbb3f7551d6de7'
yudeMacBook-Air:Tcp-DNS-proxy brite$ ls
README-zh.md		install.sh		tcpdns.py
README.md		requirements.txt	third_party
TODO.md			tcpdns.json.example	win
yudeMacBook-Air:Tcp-DNS-proxy brite$ cat requirements.txt
# Install with: `pip install -r requirements.txt`

gevent >= 1.0.1
yudeMacBook-Air:Tcp-DNS-proxy brite$ sudo python tcpdns.py -f tcpdns.json.example
Password:
Traceback (most recent call last):
  File "tcpdns.py", line 369, in <module>
    from daemon import Daemon
ImportError: cannot import name Daemon
yudeMacBook-Air:Tcp-DNS-proxy brite$ pip2 install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: gevent>=1.0.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: python-daemon>=1.5.5 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 4)) (2.2.3)
Requirement already satisfied: greenlet>=0.4.9 in /Library/Python/2.7/site-packages (from gevent>=1.0.1->-r requirements.txt (line 3)) (0.4.9)
Requirement already satisfied: lockfile>=0.10 in /Library/Python/2.7/site-packages (from python-daemon>=1.5.5->-r requirements.txt (line 4)) (0.12.2)
Requirement already satisfied: docutils in /Library/Python/2.7/site-packages (from python-daemon>=1.5.5->-r requirements.txt (line 4)) (0.14)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from python-daemon>=1.5.5->-r requirements.txt (line 4)) (18.5)
WARNING: You are using pip version 19.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
yudeMacBook-Air:Tcp-DNS-proxy brite$ sudo python tcpdns.py -f tcpdns.json.example
Traceback (most recent call last):
  File "tcpdns.py", line 369, in <module>
    from daemon import Daemon
ImportError: cannot import name Daemon
yudeMacBook-Air:Tcp-DNS-proxy brite$ 
yudeMacBook-Air:Tcp-DNS-proxy brite$ sudo python tcpdns.py -f tcpdns.json.example
Traceback (most recent call last):
  File "tcpdns.py", line 369, in <module>
    from daemon import Daemon
ImportError: cannot import name Daemon
yudeMacBook-Air:Tcp-DNS-proxy brite$ 

还是提示“ImportError: cannot import name Daemon”，怎么解决？

**Comment by luckypoem** [comment]
哦，看到这里https://github.com/henices/Tcp-DNS-proxy/issues/27#issuecomment-348377025 ，问题解决。
